"""""""""""""""""""""""""""
" General settings
"""""""""""""""""""""""""""

filetype plugin indent on       " adaptive plugin and indent according to file types
syntax enable                   " enable syntax highlight
set cursorline                  " highlight current line
set wildmenu                    " visual autocomplete for command menu
set lazyredraw                  " only redraw when necessary
set autoread                    " reload file when changed outside vim
set showmatch                   " show matching brackets
set mouse=a                     " enable mouse support
set scrolloff=7                 " keep some lines from the top and the bottom
set hidden                      " buffer becoes hidden when it is abandoned
set backspace=indent,eol,start  " backspace over autoindent, line breaks and insert
set magic                       " more natural regexp
set laststatus=2                " always show the status line
set wrap                        " allow wrap lines
set encoding=utf8               " set encoding to utf-8
set fileformats=unix,mac,dos    " set end-of-line (EOL) formats

" Line numbers
set number             " enable line numbers
set relativenumber     " show relative line numbers
" Indentation
set tabstop=4          " number of visual spaces per tab
set softtabstop=4      " number of spaces per tab when editing
set expandtab          " tabs are spaces
set shiftround         " round to multiple of shiftwidth when adjusing indentation
set shiftwidth=4       " number of spaces for each step of autoindent
set autoindent         " auto indent on a new line
" Key timeout
set notimeout          " no timeout for mappings
set ttimeout           " allow timeout for keycodes
" Search
set incsearch          " search as characters are enters
set hlsearch           " highlight matches
set ignorecase         " ignore case when searching lowercase
set smartcase          " do not ignore case when searching uppercase
" Backups
set nobackup           " disable backups
set noswapfile         " disable swapfiles

" ----8<---------- Customization

" Spell check
autocmd BufEnter *.md set spell
autocmd BufEnter *.tex set spell
" Clipboard
if $TMUX == "" && $SCREEN_NO == ""
    set clipboard+=unnamed
endif
" Jump to last position everytime
if has("autocmd")
    autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
" Treat long lines as break lines
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'
" :W sudo saves the file 
command W w !sudo tee % > /dev/null

" ----8<---------- Key bindings

" COMMA as a leader key
let mapleader=","
" Quick save and quit
nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>
nmap <leader>x :x!<cr>
" Quick highlight removal
map <silent> <leader><cr> :noh<cr>
" Quick buffer operations
map <leader>bd :bd<cr>
map <leader>l :bnext<cr>
map <leader>h :bprevious<cr>
" Quick tab operations
map <leader>tn :tabnew<cr>
map <leader>tc :tabclose<cr>


"""""""""""""""""""""""""""
" Plugin settings
"""""""""""""""""""""""""""

" Bootstrap vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync
endif

call plug#begin('~/.vim/bundle')

" Syntax
Plug 'w0rp/ale'
Plug 'maralla/completor.vim'
" Coding
Plug 'jiangmiao/auto-pairs'
Plug 'scrooloose/nerdcommenter'
Plug 'thinca/vim-quickrun'
" Navigation
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-surround'
Plug 'google/vim-searchindex'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
" Snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" Color scheme
Plug 'rakr/vim-one'
Plug 'vim-airline/vim-airline'

call plug#end()

" ----8<----------Plugin Settings

" maralla/completor.vim
let g:completor_python_binary = 'python3'

" rakr/vim-one
set background=dark
if has("termguicolors") && &t_Co == 256
    silent! colorscheme one
    if $TERM_PROGRAM != "Apple_Terminal"
        set termguicolors
        set t_8f=[38;2;%lu;%lu;%lum
        set t_8b=[48;2;%lu;%lu;%lum
    endif
endif

" vim-airline/vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" easymotion/vim-easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase  = 1
nmap <leader>s <plug>(easymotion-overwin-f2)
