####################
# zplug settings
####################
source "$HOME/.zgen/zgen.zsh"
# START of Plug
if ! zgen saved; then
zgen oh-my-zsh
zgen oh-my-zsh themes/amuse
zgen oh-my-zsh plugins/common-aliases
zgen oh-my-zsh plugins/git
zgen oh-my-zsh plugins/sudo
zgen oh-my-zsh plugins/tmux
zgen oh-my-zsh plugins/z
zgen load      zsh-users/zsh-syntax-highlighting
zgen load      tarruda/zsh-autosuggestions
zgen load      djui/alias-tips
zgen load      supercrabtree/k
zgen save
fi
# END of Plug


####################
# custom settings
####################
# Some aliases
alias t="ydcv"
# Set default editor
export EDITOR="vim"
# Add utils to PATH
export PATH=$PATH:$HOME/bin
# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
